enum ACTION_STRINGS {
  FETCH_START = '[APPOINTMENTS] FETCH START',
  FETCH_SUCCESS = '[APPOINTMENTS] FETCH SUCCESS',
  FETCH_ERROR = '[APPOINTMENTS] FETCH ERROR',

  FETCH_ONE_START = '[APPOINTMENTS] FETCH ONE START',
  FETCH_ONE_SUCCESS = '[APPOINTMENTS] FETCH ONE SUCCESS',
  FETCH_ONE_ERROR = '[APPOINTMENTS] FETCH ONE ERROR',

  FETCH_PENDING_START = '[APPOINTMENTS] FETCH PENDING START',
  FETCH_PENDING_SUCCESS = '[APPOINTMENTS] FETCH PENDING SUCCESS',
  FETCH_PENDING_ERROR = '[APPOINTMENTS] FETCH PENDING ERROR',

  FETCH_UPCOMING_START = '[APPOINTMENTS] FETCH UPCOMING START',
  FETCH_UPCOMING_SUCCESS = '[APPOINTMENTS] FETCH UPCOMING SUCCESS',
  FETCH_UPCOMING_ERROR = '[APPOINTMENTS] FETCH UPCOMING ERROR',

  RESERVE_START = '[APPOINTMENTS] RESERVE START',
  RESERVE_SUCCESS = '[APPOINTMENTS] RESERVE SUCCESS',
  RESERVE_ERROR = '[APPOINTMENTS] RESERVE ERROR',

  ACCEPT_START = '[APPOINTMENTS] ACCEPT START',
  ACCEPT_SUCCESS = '[APPOINTMENTS] ACCEPT SUCCESS',
  ACCEPT_ERROR = '[APPOINTMENTS] ACCEPT ERROR',

  CONFIRM_START = '[APPOINTMENTS] CONFIRM START',
  CONFIRM_SUCCESS = '[APPOINTMENTS] CONFIRM SUCCESS',
  CONFIRM_ERROR = '[APPOINTMENTS] CONFIRM ERROR',

  CANCEL_START = '[APPOINTMENTS] CANCEL START',
  CANCEL_SUCCESS = '[APPOINTMENTS] CANCEL SUCCESS',
  CANCEL_ERROR = '[APPOINTMENTS] CANCEL ERROR',

  REJECT_START = '[APPOINTMENTS] REJECT START',
  REJECT_SUCCESS = '[APPOINTMENTS] REJECT SUCCESS',
  REJECT_ERROR = '[APPOINTMENTS] REJECT ERROR',

  GET_SERVER_TIME_START = '[APPOINTMENTS] GET SERVER TIME START',
  GET_SERVER_TIME_SUCCESS = '[APPOINTMENTS] GET SERVER TIME SUCCESS',
  GET_SERVER_TIME_ERROR = '[APPOINTMENTS] GET SERVER TIME ERROR',

  CLEAR_CURRENT = '[APPOINTMENTS] CLEAR CURRENT',

  RESET_ERROR = '[APPOINTMENTS] RESET ERROR',
}

export default ACTION_STRINGS;
