enum ACTION_STRINGS {
  FETCH_START = '[CATEGORIES] FETCH START',
  FETCH_SUCCESS = '[CATEGORIES] FETCH SUCCESS',
  FETCH_ERROR = '[CATEGORIES] FETCH ERROR',

  RESET_ERROR = '[CATEGORIES] RESET ERROR',
}

export default ACTION_STRINGS;
