enum ACTION_STRINGS {
  FETCH_START = '[REQUIRED DOCUMENTATION] FETCH START',
  FETCH_SUCCESS = '[REQUIRED DOCUMENTATION] FETCH SUCCESS',
  FETCH_ERROR = '[REQUIRED DOCUMENTATION] FETCH ERROR',

  NEW_DOC_START = '[REQUIRED DOCUMENTATION] NEW DOC START',
  NEW_DOC_SUCCESS = '[REQUIRED DOCUMENTATION] NEW DOC SUCCESS',
  NEW_DOC_ERROR = '[REQUIRED DOCUMENTATION] NEW DOC ERROR',

  UPDATE_START = '[REQUIRED DOCUMENTATION] UPDATE START',
  UPDATE_SUCCESS = '[REQUIRED DOCUMENTATION] UPDATE SUCCESS',
  UPDATE_ERROR = '[REQUIRED DOCUMENTATION] UPDATE ERROR',

  DELETE_START = '[REQUIRED DOCUMENTATION] DELETE START',
  DELETE_SUCCESS = '[REQUIRED DOCUMENTATION] DELETE SUCCESS',
  DELETE_ERROR = '[REQUIRED DOCUMENTATION] DELETE ERROR',

  RESET_ERROR = '[REQUIRED DOCUMENTATION] RESET ERROR',
}

export default ACTION_STRINGS;
