enum ACTION_STRINGS {
  FETCH_START = '[CONVERSATIONS] FETCH START',
  FETCH_SUCCESS = '[CONVERSATIONS] FETCH SUCCESS',
  FETCH_ERROR = '[CONVERSATIONS] FETCH ERROR',

  FETCH_ONE_START = '[CONVERSATIONS] FETCH ONE START',
  FETCH_ONE_SUCCESS = '[CONVERSATIONS] FETCH ONE SUCCESS',
  FETCH_ONE_ERROR = '[CONVERSATIONS] FETCH ONE ERROR',

  CLEAR_CONVERSATION = '[CONVERSATIONS] CLEAR CONVERSATION',

  ADD_LAST_MESSAGE = '[CONVERSATIONS] ADD LAST MESSAGE',

  RESET_ERROR = '[CONVERSATIONS] RESET ERROR',
}

export default ACTION_STRINGS;
