enum ACTION_STRINGS {
  FETCH_START = '[THERAPISTS] FETCH START',
  FETCH_SUCCESS = '[THERAPISTS] FETCH SUCCESS',
  FETCH_ERROR = '[THERAPISTS] FETCH ERROR',

  FETCH_PROFILE_START = '[THERAPISTS] FETCH PROFILE START',
  FETCH_PROFILE_SUCCESS = '[THERAPISTS] FETCH PROFILE SUCCESS',
  FETCH_PROFILE_ERROR = '[THERAPISTS] FETCH PROFILE ERROR',

  RESET_ERROR = '[THERAPISTS] RESET ERROR',
}

export default ACTION_STRINGS;
